package AppPro.domain.error;

public enum ErrorCode {

    USERNAME_EMPTY,
    USERNAME_TOO_SHORT,
    USERNAME_TOO_LONG,
    USER_NOT_FOUND,
    USERNAME_ALREADY_EXISTS,
    USER_SEARCH_HIMSELF,
    USER_NOT_PARTICIPANT,
    SAME_USERS_IN_CHAT,

    MESSAGE_TOO_LONG,
    MESSAGE_EMPTY,

    ID_EMPTY,

    PASSWORD_MISMATCH,
    PASSWORD_TOO_SHORT,
    PASSWORD_EMPTY,
    PASSWORD_TOO_LONG,

    CHAT_ALREADY_EXISTS,
    CHAT_NOT_FOUND,

}
