package main.domain.error;

public enum ErrorCode {

    USER_NOT_FOUND,
    USERNAME_INVALID,
    USER_NOT_PARTICIPANT,
    USER_SEARCH_HIMSELF,
    SAME_USERS,

    MESSAGE_TOO_LONG,
    MESSAGE_EMPTY,

    ID_EMPTY,

    PASSWORD_MISMATCH,
    PASSWORD_TOO_SHORT,
    PASSWORD_EMPTY,
    PASSWORD_TOO_LONG,

    CHAT_ALREADY_EXISTS,
    CHAT_NOT_FOUND,

}
